//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public decimal ID { get; set; }
        public System.DateTime Data { get; set; }
        public decimal StatusID { get; set; }
        public decimal OborudovanieID { get; set; }
        public decimal KlientID { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual Status Status { get; set; }
    }
}
